/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as KennisbankRouteImport } from './routes/kennisbank'
import { Route as HulpBijErfenisRouteImport } from './routes/hulp-bij-erfenis'
import { Route as BijLevenRegelenRouteImport } from './routes/bij-leven-regelen'
import { Route as IndexRouteImport } from './routes/index'

const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const KennisbankRoute = KennisbankRouteImport.update({
  id: '/kennisbank',
  path: '/kennisbank',
  getParentRoute: () => rootRouteImport,
} as any)
const HulpBijErfenisRoute = HulpBijErfenisRouteImport.update({
  id: '/hulp-bij-erfenis',
  path: '/hulp-bij-erfenis',
  getParentRoute: () => rootRouteImport,
} as any)
const BijLevenRegelenRoute = BijLevenRegelenRouteImport.update({
  id: '/bij-leven-regelen',
  path: '/bij-leven-regelen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
  '/kennisbank': typeof KennisbankRoute
  '/over-ons': typeof OverOnsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
  '/kennisbank': typeof KennisbankRoute
  '/over-ons': typeof OverOnsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
  '/kennisbank': typeof KennisbankRoute
  '/over-ons': typeof OverOnsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bij-leven-regelen'
    | '/hulp-bij-erfenis'
    | '/kennisbank'
    | '/over-ons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bij-leven-regelen'
    | '/hulp-bij-erfenis'
    | '/kennisbank'
    | '/over-ons'
  id:
    | '__root__'
    | '/'
    | '/bij-leven-regelen'
    | '/hulp-bij-erfenis'
    | '/kennisbank'
    | '/over-ons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BijLevenRegelenRoute: typeof BijLevenRegelenRoute
  HulpBijErfenisRoute: typeof HulpBijErfenisRoute
  KennisbankRoute: typeof KennisbankRoute
  OverOnsRoute: typeof OverOnsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kennisbank': {
      id: '/kennisbank'
      path: '/kennisbank'
      fullPath: '/kennisbank'
      preLoaderRoute: typeof KennisbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hulp-bij-erfenis': {
      id: '/hulp-bij-erfenis'
      path: '/hulp-bij-erfenis'
      fullPath: '/hulp-bij-erfenis'
      preLoaderRoute: typeof HulpBijErfenisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bij-leven-regelen': {
      id: '/bij-leven-regelen'
      path: '/bij-leven-regelen'
      fullPath: '/bij-leven-regelen'
      preLoaderRoute: typeof BijLevenRegelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BijLevenRegelenRoute: BijLevenRegelenRoute,
  HulpBijErfenisRoute: HulpBijErfenisRoute,
  KennisbankRoute: KennisbankRoute,
  OverOnsRoute: OverOnsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
