/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HulpBijErfenisRouteImport } from './routes/hulp-bij-erfenis'
import { Route as BijLevenRegelenRouteImport } from './routes/bij-leven-regelen'
import { Route as IndexRouteImport } from './routes/index'

const HulpBijErfenisRoute = HulpBijErfenisRouteImport.update({
  id: '/hulp-bij-erfenis',
  path: '/hulp-bij-erfenis',
  getParentRoute: () => rootRouteImport,
} as any)
const BijLevenRegelenRoute = BijLevenRegelenRouteImport.update({
  id: '/bij-leven-regelen',
  path: '/bij-leven-regelen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bij-leven-regelen': typeof BijLevenRegelenRoute
  '/hulp-bij-erfenis': typeof HulpBijErfenisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bij-leven-regelen' | '/hulp-bij-erfenis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bij-leven-regelen' | '/hulp-bij-erfenis'
  id: '__root__' | '/' | '/bij-leven-regelen' | '/hulp-bij-erfenis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BijLevenRegelenRoute: typeof BijLevenRegelenRoute
  HulpBijErfenisRoute: typeof HulpBijErfenisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hulp-bij-erfenis': {
      id: '/hulp-bij-erfenis'
      path: '/hulp-bij-erfenis'
      fullPath: '/hulp-bij-erfenis'
      preLoaderRoute: typeof HulpBijErfenisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bij-leven-regelen': {
      id: '/bij-leven-regelen'
      path: '/bij-leven-regelen'
      fullPath: '/bij-leven-regelen'
      preLoaderRoute: typeof BijLevenRegelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BijLevenRegelenRoute: BijLevenRegelenRoute,
  HulpBijErfenisRoute: HulpBijErfenisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
